[metadata]
name = "Whoami"
description = "Simple HTTP service that prints OS information and HTTP request to output"
icon = "globe"
website = "https://github.com/traefik/whoami"
category = "utilities"
backup_supported = false

[defaults]
WHOAMI_PORT = "8081"

[health]
port = 8081
path = "/api"
interval_secs = 10
