services:
  memos:
    image: neosmemo/memos:stable
    container_name: myground-memos
    restart: unless-stopped
    ports:
      - "${BIND_IP}:${EXIT_PORT}:5230"
    healthcheck:
      test: wget -q --spider http://localhost:5230/ || exit 1
      interval: 3s
      timeout: 3s
      retries: 20
      start_period: 3s
    volumes:
      - ${STORAGE_data}:/var/opt/memos
