services:
  pihole:
    image: pihole/pihole:latest
    container_name: myground-pihole
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "${SERVER_IP}:53:53/tcp"
      - "${SERVER_IP}:53:53/udp"
      - "${BIND_IP}:${PIHOLE_PORT}:80"
    volumes:
      - ${STORAGE_pihole_config}:/etc/pihole
      - ${STORAGE_dnsmasq_config}:/etc/dnsmasq.d
    environment:
      FTLCONF_webserver_api_password: "${PIHOLE_PASSWORD}"
      FTLCONF_dns_listeningMode: "all"
    cap_add:
      - NET_ADMIN
