services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: myground-radarr
    restart: unless-stopped
    ports:
      - "${BIND_IP}:${EXIT_PORT}:7878"
    volumes:
      - ${STORAGE_config}:/config
      - ${MOVIES_PATH}:/movies
      - ${DOWNLOADS_PATH}:/downloads
    healthcheck:
      test: curl -f http://localhost:7878/ping || exit 1
      interval: 3s
      timeout: 3s
      retries: 30
      start_period: 10s
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Etc/UTC
